USE [DM_TECH_APPLICATION_DEVELOPMENT]
GO

/****** Object:  View [SOURCE].[ADP_EMPLOYEE]    Script Date: 1/20/2026 2:04:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [SOURCE].[ADP_EMPLOYEE] AS 
SELECT
     [EMPNO] [ASSOCIATE_ID]
    ,[ACTIVEST] [POSITION_STATUS]
    ,[DEPT] [HOME_DEPARTMENT_CODE]
    ,[EMAIL] [WORK_EMAIL]
    ,[JOB_TITLE_CODE] [JOB_CODE]
    ,[JOBTITLE] [JOB_TITLE_DESCRIPTION]
    ,[FNAME] [FIRST_NAME]
    ,[LNAME] [LAST_NAME]
    ,[ORIGHIRE] [HIRE_DATE]
    ,[TERMDATE] [TERMINATION_DATE]
    ,[SUPNO] [REPORTS_TO_ASSOCIATE_ID]
    ,[WPHONE] [WORK_PHONE]
    ,[FTE] [FT_PT_INDICATOR]
    ,[ASOF] [ASOF]
FROM ADP.HISTORY.DSUSER
GO


