// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pto.track.data;

#nullable disable

namespace pto.track.data.Migrations
{
    [DbContext(typeof(PtoTrackDbContext))]
    [Migration("20251118021833_ChangeIdToGuid")]
    partial class ChangeIdToGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pto.track.data.AbsenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AbsenceRequests");
                });

            modelBuilder.Entity("pto.track.data.SchedulerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("resource");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("pto.track.data.SchedulerResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Resource A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resource B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resource C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Resource D"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Resource E"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Resource F"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Resource G"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Resource H"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Resource I"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Resource J"
                        });
                });

            modelBuilder.Entity("pto.track.data.AbsenceRequest", b =>
                {
                    b.HasOne("pto.track.data.SchedulerResource", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("pto.track.data.SchedulerResource", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
