// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pto.track.data;

#nullable disable

namespace pto.track.data.Migrations
{
    [DbContext(typeof(PtoTrackDbContext))]
    [Migration("20251119213642_FixResourcesIdIdentity")]
    partial class FixResourcesIdIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pto.track.data.AbsenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AbsenceRequests");
                });

            modelBuilder.Entity("pto.track.data.SchedulerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("resource");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("pto.track.data.SchedulerResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDirectoryId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprover")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource A",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource B",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource C",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource D",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource E",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource F",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource G",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource H",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource I",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resource J",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("pto.track.data.AbsenceRequest", b =>
                {
                    b.HasOne("pto.track.data.SchedulerResource", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("pto.track.data.SchedulerResource", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("pto.track.data.SchedulerResource", b =>
                {
                    b.HasOne("pto.track.data.SchedulerResource", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
