// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pto.track.data;

#nullable disable

namespace pto.track.data.Migrations
{
    [DbContext(typeof(PtoTrackDbContext))]
    [Migration("20260121002603_AddAdpFieldsToResource")]
    partial class AddAdpFieldsToResource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pto.track.data.AbsenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AbsenceRequests");
                });

            modelBuilder.Entity("pto.track.data.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Name = "Group 1"
                        });
                });

            modelBuilder.Entity("pto.track.data.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDirectoryId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprover")
                        .HasColumnType("bit");

                    b.Property<string>("JobCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerAssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssociateId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveDirectoryId = "mock-ad-guid-employee",
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "employee@example.com",
                            EmployeeNumber = "EMP001",
                            GroupId = 1,
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Employee 1",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            ActiveDirectoryId = "mock-ad-guid-employee2",
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "employee2@example.com",
                            EmployeeNumber = "EMP002",
                            GroupId = 1,
                            IsActive = true,
                            IsApprover = false,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Employee 2",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 3,
                            ActiveDirectoryId = "mock-ad-guid-manager",
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@example.com",
                            EmployeeNumber = "MGR001",
                            GroupId = 1,
                            IsActive = true,
                            IsApprover = true,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Manager",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            ActiveDirectoryId = "mock-ad-guid-approver",
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "approver@example.com",
                            EmployeeNumber = "APR001",
                            GroupId = 1,
                            IsActive = true,
                            IsApprover = true,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Approver",
                            Role = "Approver"
                        },
                        new
                        {
                            Id = 5,
                            ActiveDirectoryId = "mock-ad-guid-admin",
                            CreatedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            EmployeeNumber = "ADMIN001",
                            GroupId = 1,
                            IsActive = true,
                            IsApprover = true,
                            ModifiedDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Administrator",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("pto.track.data.SchedulerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "resource");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("pto.track.data.AbsenceRequest", b =>
                {
                    b.HasOne("pto.track.data.Resource", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("pto.track.data.Resource", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("pto.track.data.Resource", b =>
                {
                    b.HasOne("pto.track.data.Models.Group", "Group")
                        .WithMany("Resources")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pto.track.data.Resource", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Group");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("pto.track.data.Models.Group", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
