// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pto.track.data;

#nullable disable

namespace pto.track.data.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    partial class SchedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Project.Models.SchedulerEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("resource");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Project.Models.SchedulerResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Resource A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resource B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resource C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Resource D"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Resource E"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Resource F"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Resource G"
                        },
                        new
                        {
                            Id = 8,
                            Name = "PResource H"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Resource I"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Resource J"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
